---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: device-gateway-sa
  namespace: device-operator-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: device-gateway-role
  namespace: device-operator-system
rules:
- apiGroups: ["devices.example.com"]
  resources: ["deviceregistrations"]
  verbs: ["create", "get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: device-gateway-rolebinding
  namespace: device-operator-system
subjects:
- kind: ServiceAccount
  name: device-gateway-sa
roleRef:
  kind: Role
  name: device-gateway-role
  apiGroup: rbac.authorization.k8s.io