apiVersion: v1
kind: Service
metadata:
  name: device-gateway-service
  namespace: device-operator-system
spec:
  type: NodePort
  selector:
    app: device-gateway
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
    nodePort: 30007 # Porta fissa per i test