# permissions for end users to edit deviceregistrations.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: device-operator
    app.kubernetes.io/managed-by: kustomize
  name: deviceregistration-editor-role
rules:
- apiGroups:
  - devices.devices.example.com
  resources:
  - deviceregistrations
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - devices.devices.example.com
  resources:
  - deviceregistrations/status
  verbs:
  - get
